# Generated by Django 5.1.5 on 2025-01-19 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='courses/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('React', 'React'), ('Angular', 'Angular'), ('Vue', 'Vue'), ('Nodejs', 'Nodejs')], default='Python', max_length=8)),
            ],
        ),
    ]
