# Generated by Django 5.1.5 on 2025-01-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course_Category',
        ),
    ]
