# Generated by Django 5.1.5 on 2025-01-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_course_category_image2_course_category_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_category',
            name='category_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course_category',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
